version: '3'
services:
#  reverse-proxy:
#    container_name: 'reverse-proxy'
#    image: nginx

  server:
    container_name: 'server'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "NODE_ENV=${NODE_ENV:-production}"

  mysql:
    container_name: 'mysql'
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQLDB_DATABASE=tier
    volumes:
      - ./data/setup.sql:/docker-entrypoint-initdb.d/setup.sql
